- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Determine Docker Compose latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -i \"browser_download_url.*linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_compose_version

    - name: Install Docker Compose
      become: yes
      get_url:
        url: "{{ docker_compose_version.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Add Docker APT package key
      become: yes
      get_url:
        url: https://download.docker.com/linux/{{ distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64, signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distribution | lower }} {{ ansible_distribution_release }} stable
        filename: docker
        update_cache: no
      register: apt_repository_docker

    - name: Install Docker engine
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli

    - name: Create "docker" group
      group:
        name: "docker"
        state: present
      become: yes
        
    - name: Enable Docker engine for current user
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes
      become: yes
   
    - name: Reset connection so docker group is picked up.
      meta: reset_connection
      
    - name: Determine Docker Machine latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/machine/releases/latest | grep \"browser_download_url.*Linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_machine_version

    - name: Install Docker Machine
      become: yes
      get_url:
        url: "{{ docker_machine_version.stdout }}"
        dest: /usr/local/bin/docker-machine
        mode: 0755
